-- creating tables

CREATE TABLE User (
  uid INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  user_name VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  isAdmin BOOL NOT NULL
);

CREATE TABLE Media (
  tid INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  release_date DATE NOT NULL,
  duration INT,
  poster_url VARCHAR(255),
  trailer_url VARCHAR(255)
);

CREATE TABLE Languages(
  lid INT AUTO_INCREMENT PRIMARY KEY,
  language VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Media_Languages(
  tid INT,
  lid INT, 
  PRIMARY KEY (tid,lid),
  FOREIGN KEY (tid) REFERENCES Media (tid) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (lid) REFERENCES Languages (lid) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Ratings (
  tid INT NOT NULL,
  uid INT NOT NULL,
  rating DECIMAL(2,1) NOT NULL,
  PRIMARY KEY(tid,uid),
  FOREIGN KEY (tid) REFERENCES Media(tid) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (uid) REFERENCES User(uid) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE View_History (
  tid INT NOT NULL,
  uid INT NOT NULL,
  watched_on TIMESTAMP,
  PRIMARY KEY(tid, uid, watched_on),
  FOREIGN KEY (tid) REFERENCES Media(tid) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (uid) REFERENCES User(uid) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Genres(
  gid INT AUTO_INCREMENT PRIMARY KEY,
  genre VARCHAR(50)
);

CREATE TABLE Media_Genres(
  gid INT,
  tid INT,
  PRIMARY KEY (gid,tid),
  FOREIGN KEY (gid) REFERENCES Genres(gid) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (tid) REFERENCES Media(tid) ON UPDATE CASCADE ON DELETE CASCADE
);